import { IProject } from "../models/IProject";

export const projects: IProject[] = [
  {
    id: 1,
    name: "Advaantics",
    role: "Full Stack Developer",
    skills: [
      "Node",
      "Express",
      "PostgreSQL",
      "Nexe",
      "Tauri",
      "Angular",
      "ECharts",
    ],
    client: "SIEMENS",
    points: [
      "Saved 35% on setup time by leading the development of Advaantics, a web app for industrial machine monitoring, integrating OPCUA and Siemens FOCUS servers.",
      "Boosted data operations by 40% by designing a multi-service backend architecture in Node.js and Express, enhancing user and machine data management.",
      "Reduced data lag by 60% with an API service featuring WebSocket connectivity for real-time synchronization and MQTT for seamless interaction.",
      "Increased operational efficiency by 20% and cut reporting time by 15% by developing tools for time-series data handling and performance tracking",
      "Accelerated deployment by 50% through optimizing frontend performance with custom Angular components and caching strategies, packaging the application with Nexe within 4 months.",
    ],
    link: "/projects/advaantics",
  },
  {
    id: 2,
    name: "IGBT Health App",
    role: "Full Stack Developer",
    skills: [
      "Node",
      "Express",
      "PostgreSQL",
      "Nexe",
      "Tauri",
      "Angular",
      "ECharts",
    ],
    client: "SIEMENS",
    points: [
      "Saved 35% on setup time by leading the development of Advaantics, a web app for industrial machine monitoring, integrating OPCUA and Siemens FOCUS servers.",
      "Boosted data operations by 40% by designing a multi-service backend architecture in Node.js and Express, enhancing user and machine data management.",
      "Reduced data lag by 60% with an API service featuring WebSocket connectivity for real-time synchronization and MQTT for seamless interaction.",
      "Increased operational efficiency by 20% and cut reporting time by 15% by developing tools for time-series data handling and performance tracking",
      "Accelerated deployment by 50% through optimizing frontend performance with custom Angular components and caching strategies, packaging the application with Nexe within 4 months.",
    ],
    link: "/projects/igbt-health-app",
  },
  {
    id: 3,
    name: "Google Customer Experience",
    role: "Full Stack Developer",
    skills: [
      "Node",
      "Express",
      "PostgreSQL",
      "Nexe",
      "Tauri",
      "Angular",
      "ECharts",
    ],
    client: "Google",
    points: [
      "Saved 35% on setup time by leading the development of Advaantics, a web app for industrial machine monitoring, integrating OPCUA and Siemens FOCUS servers.",
      "Boosted data operations by 40% by designing a multi-service backend architecture in Node.js and Express, enhancing user and machine data management.",
      "Reduced data lag by 60% with an API service featuring WebSocket connectivity for real-time synchronization and MQTT for seamless interaction.",
      "Increased operational efficiency by 20% and cut reporting time by 15% by developing tools for time-series data handling and performance tracking",
      "Accelerated deployment by 50% through optimizing frontend performance with custom Angular components and caching strategies, packaging the application with Nexe within 4 months.",
    ],
    link: "/projects/google-customer-experience",
  },
  {
    id: 4,
    name: "CHUBB: Mergers & Acquisitions",
    role: "Full Stack Developer",
    skills: [
      "Node",
      "Express",
      "PostgreSQL",
      "Nexe",
      "Tauri",
      "Angular",
      "ECharts",
    ],
    client: "CHUBB",
    points: [
      "Saved 35% on setup time by leading the development of Advaantics, a web app for industrial machine monitoring, integrating OPCUA and Siemens FOCUS servers.",
      "Boosted data operations by 40% by designing a multi-service backend architecture in Node.js and Express, enhancing user and machine data management.",
      "Reduced data lag by 60% with an API service featuring WebSocket connectivity for real-time synchronization and MQTT for seamless interaction.",
      "Increased operational efficiency by 20% and cut reporting time by 15% by developing tools for time-series data handling and performance tracking",
      "Accelerated deployment by 50% through optimizing frontend performance with custom Angular components and caching strategies, packaging the application with Nexe within 4 months.",
    ],
    link: "/projects/chubb-mergers-acquisitions",
  },
];
